from coordinates import *
DEFAULT = 0
ACCEPT = 1
UNACCEPT = 0
CHECK = 1
WON = 2

DEFAULT_N = 20
DEFAULT_M = 20
DEFAULT_K = 8

DEFAULT_LOCATION = Coordinates(-1,-1)
DEFAULT_LOCATION_PLAYER = Coordinates(4,0)
DEFAULT_TREASURE_LOCATION = Coordinates(18,8)

N = DEFAULT_N
M = DEFAULT_M
K = DEFAULT_K
LOCATION_PLAYER = DEFAULT_LOCATION_PLAYER

TREASURE_LOCATION = DEFAULT_TREASURE_LOCATION

